name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Extract Git Commit SHA
      id: vars
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build & Push Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/first-task-docker:${{ env.COMMIT_SHA }}
        docker build . -t $IMAGE_NAME
        docker push $IMAGE_NAME
        # Tag the image as latest as well
        docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/first-task-docker:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/first-task-docker:latest

    - name: Output Image Name
      run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/first-task-docker:${{ env.COMMIT_SHA }}" >> $GITHUB_ENV
