name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/first-task-docker:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/first-task-docker:latest
